
const gametypeArray = [
    "Parkour",
    "Simulator",
    "Minigame",
    "KitPvP",
    "Escape Room",
    "Roleplay",
    "Maze",
    "Event House",
    "PVP"
];

const topicsArray = [
    "Underwater adventure",
    "Space odyssey",
    "Zookeeper's day out",
    "Secret recipes quest",
    "Time-traveling wonders",
    "Steampunk funland",
    "Magic school",
    "Wild west cowboy",
    "Ancient civilization",
    "Superhero training camp",
    "Dinosaur discovery tour",
    "Alien planet",
    "Futuristic city",
    "Treasure hunt",
    "Post-apocalyptic survival quest",
    "Medieval kingdom quests",
    "Art detective mission",
    "Spy missions in action",
    "Fairytale adventures",
    "Parallel world journey",
    "Mythical creatures encounter",
    "Pirate treasure hunt",
    "Movie star experience",
    "Famous history adventures",
    "Haunted mansion mystery",
    "Puzzle-solving adventures",
    "Astronaut space training",
    "Robot friends adventure",
    "Day with a celebrity",
    "Antarctic expedition",
    "Virtual reality funfair",
    "Ancient artifacts quest",
    "Desert adventure caravan",
    "Ghost-hunting in ruins",
    "Renaissance artist journey",
    "Prison break fun",
    "Parallel dimension hopping",
    "Amazon rainforest exploration",
    "Time loop escapades",
    "Sci-fi planet exploration",
    "Oceanic wildlife safari",
    "Abandoned theme park adventure",
    "Jungle survival challenge",
    "Ice age frozen adventure",
    "Deep-sea diving treasure hunt",
    "Space adventure as stowaways",
    "Diplomatic missions to aliens",
    "Zombie apocalypse fun",
    "Virtual reality gaming quest",
    "Alchemy potions adventure",
    "Renaissance alchemist journey",
    "Forest guardian adventure",
    "Casino heist escapades",
    "Giant mecha robot battle",
    "Gladiator arena challenges",
    "Museum art heist mission",
    "Superpowers training camp",
    "Time-traveling detective journey",
    "Knights and dragon quests",
    "Spy agency infiltration",
    "Journey to the Earth's core",
    "Egyptian pyramid exploration",
    "Enchanted forest survival",
    "Dinosaur zookeeper experience",
    "Galactic bounty hunter",
    "Cyberpunk city adventures",
    "Seven wonders exploration",
    "Virtual reality sports fun",
    "Post-apocalyptic city rescue",
    "Supervillain's lair escape",
    "Mountain climbing adventure",
    "Time-traveling historic events",
    "Mythical creature zoo hunt",
    "North Pole expedition",
    "Space pirates treasure hunt",
    "Art recovery from thieves",
    "Amazon rainforest exploration",
    "Virtual reality horror quest",
    "Rebuilding after a disaster",
    "Secret lab scientific quests",
    "Protecting wildlife adventure",
    "Time-traveling archaeologist",
    "Haunted castle mystery",
    "Spy missions in action",
    "Magical fairyland journey",
    "Robot gladiator battles",
    "Building a futuristic city",
    "Lost civilization discovery",
    "Meeting famous figures",
    "Lost alien civilizations",
    "Surviving a volcanic island",
    "Monster hunter challenges",
    "Deep-space mining adventure",
    "Escape from a maze",
    "Post-apocalyptic wasteland quest",
    "Futuristic city espionage",
    "Legendary creature adventure",
    "Futuristic city racing",
    "Cyberworld adventure",
    "Space station exploration",
    "Pizzeria quest",
    "Modern Space adventure"
];

function generateidea() {
    const gameType = gametypeArray[Math.floor(Math.random() * gametypeArray.length)];
    const gameTopic = topicsArray[Math.floor(Math.random() * topicsArray.length)];
    Client.showTitle(`&eMake a &6&l${gameType}`, `&e&oabout &6${gameTopic}`, 8, 100, 8);
    World.playSound("note.pling", 1.0, 2.0)
}

register("command", () => {
    generateidea();
}).setName("generateidea");

module.exports = {
    generateidea
}